spring:
  application:
    name: spring-mvc-practice

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB  #? ???
      max-request-size: 10MB #? ???


blog:
  file-directory: /Users/milk/Desktop/Codeit-7th-develop